---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seckill-deployment
  namespace: team2
  labels:
    app: seckill
spec:
  replicas: 2 # 副本数量。 创建ReplicaSet管理
  selector:   # 选择器
    matchLabels:  # 选择 匹配标签 app=seckill 的 Pods
      app: seckill
  template:  # Pod模版
    metadata:
      labels:  # Pod 标签
        app: seckill
    spec:
      containers:  # Pod包含的容器
        - name: seckill-container
          image: yinli2020-docker.pkg.coding.net/beijing-backend/team2/seckillservice:v0.1
          env: # 环境变量
            - name: SECKILL_VERSION
              value: v0.1
          ports:  # 容器暴露的端口号
            - containerPort: 50051
      imagePullSecrets:
        - name: yinli-coding-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: seckill-service
  namespace: team2
spec:
  selector:  # 匹配标签 app=seckill 的 Pods
    app: seckill
  ports:
    - protocol: TCP  # 服务协议
      port: 50051   # 服务端口号
      targetPort: 50053 # 目标Pod的端口号
      name: http
