CREATE TABLE `mytest`.`onSaleGood`  (
  `道具ID` int UNSIGNED NOT NULL,
  `道具名称` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `售价` int UNSIGNED NOT NULL DEFAULT 10,
  `所属用户ID` int UNSIGNED NOT NULL,
  `道具属性` int NOT NULL DEFAULT 0 COMMENT '0为普通,1为特殊' ,
  `数量` int NOT NULL ,
  `商城ID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`商城ID`),
  CONSTRAINT `道具外键` FOREIGN KEY (`道具ID`) REFERENCES `mytest`.`good` (`道具ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `所属玩家ID外键` FOREIGN KEY (`所属用户ID`) REFERENCES `mytest`.`user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `名称外键` FOREIGN KEY (`道具名称`) REFERENCES `mytest`.`good` (`道具名称`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB CHARACTER SET = utf8