CREATE TABLE `mytest`.`trade`  (
  `订单ID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `订单时间` varchar(255) NOT NULL DEFAULT '',
  `订单类型` int UNSIGNED NOT NULL COMMENT '1为出售，2为购买',
  `道具ID` int UNSIGNED NOT NULL COMMENT '流转的道具ID',
  `玩家ID` int UNSIGNED NOT NULL,
  `交易金额` int UNSIGNED NOT NULL,
  PRIMARY KEY (`订单ID`),
  CONSTRAINT `道具` FOREIGN KEY (`道具ID`) REFERENCES `mytest`.`good` (`道具ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `玩家` FOREIGN KEY (`玩家ID`) REFERENCES `mytest`.`user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB CHARACTER SET = utf8