-- 从excel导入后，设置默认值和类型

ALTER TABLE `mytest`.`good` 
MODIFY COLUMN `道具ID` int(4) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
MODIFY COLUMN `道具名称` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `道具ID`,
MODIFY COLUMN `道具类别` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `道具名称`,
MODIFY COLUMN `最低使用等级` int(3) UNSIGNED NOT NULL DEFAULT 0 AFTER `道具类别`,
MODIFY COLUMN `适用职业` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `最低使用等级`,
MODIFY COLUMN `物品档次` int(2) UNSIGNED NOT NULL DEFAULT 0 AFTER `适用职业`,
MODIFY COLUMN `物品颜色` int(1) UNSIGNED NOT NULL DEFAULT 0 AFTER `物品档次`;