---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-deployment
  namespace: team2
  labels:
    app: mall
spec:
  replicas: 2 # 副本数量。 创建ReplicaSet管理
  selector:   # 选择器
    matchLabels:  # 选择 匹配标签 app=mall 的 Pods
      app: mall
  template:  # Pod模版
    metadata:
      labels:  # Pod 标签
        app: mall
    spec:
      containers:  # Pod包含的容器
        - name: mall-container
          image: yinli2020-docker.pkg.coding.net/beijing-backend/team2/mallservice:v0.4
          env: # 环境变量
            - name: MALL_VERSION
              value: v0.4
          ports:  # 容器暴露的端口号
            - containerPort: 50051
      imagePullSecrets:
        - name: yinli-coding-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: mall-service
  namespace: team2
spec:
  selector:  # 匹配标签 app=mall 的 Pods
    app: mall
  ports:
    - protocol: TCP  # 服务协议
      port: 50051   # 服务端口号
      targetPort: 50051 # 目标Pod的端口号
      name: http
